---
title: "STA 523 Final Project"
author: "Dipesh Gautam, Radhika Anand, Haosheng Luo, Siyang Li"
date: "12/12/2014"
output: html_document
---

For this project, we have built a package called `concomp` to detect connected components and holes and their boundaries in an image or a logical matrix.

##Motivation
While working on 523 Homework-3, where we had to detect Manhattan precinct boundaries, we had data points in all of Manhattan apart from the Central Park area. While trying to detect the Central Park, we were looking for functions to detect holes and boundaries and hence decided to create a package with functions for the same.

##Functions
We have written the following three functions in our package:

1) `conLabel()` Assigns labels to connected components in a logical matrix

2) `conBoundaries()` Detects internal and external boundaries of connected components in a logical matrix

3) `imgMat()` Converts a PNG file to a logical matrix

##Methodology

#####1) `conLabel(x,N=4)` Assigns labels to connected components in a logical matrix

#####Inputs

1) A logical matrix whose connected components are to be labeled

2) An integer to specify 4 or 8 connectivity

#####Output

Matrix with connected components detected and separately labeled

#####Algorithm

We have implemented a single-pass algorithm where we traverse the matrix row wise and label the connected components using 4 or 8-connectivity as specified by the user. In 4-connectivity, we look at the top, left, right and bottom neighbor of each cell and in 8-connectivity we check all 8 neighbors.

#####Steps

1) A connected-component matrix is initialized to size of the input matrix

2) A `mark` is initialized and incremented for every detected component in the matrix

3) A row-major scan is started for the entire matrix

4) If a component cell is detected, the following steps are repeated while (`index` !=0) 
+ Set the corresponding cell to 0 in the matrix
+ A vector `index` is updated with all the neighboring cells (4 or 8) of the currently set cells 
+ Only the unique cells are retained 
+ Set the cells indicated by `index` to `mark` in the connected-component matrix

5) Increment the marker for another component

6) Deal with edge cases on the fly

#####2) `conBoundaries(x,N=4)` Detects internal and external boundaries of connected components in a logical matrix



#####3) `imgMat(x)` Converts a PNG file to a logical matrix

#####Input

Image or image path

#####Output

A logical matrix indicating white or black pixels of the image

#####Algorithm

Here we convert a .png image file to a logical matrix to be further used as an input to conLabel and conBoundaries. 0 indicates white (and slightly offwhite) pixels and 1 indicates colored pixels of a high-contrast image.

#####Steps

1) Read the image using command `readPNG` from package `png`

2) Sum up the layers of the 3-D matrix obtained and normalize the data to be between 0 and 1 such that 0 indicates white and black indicates 1

3) Set all values greater then 0.1 to 1 and less than or equal to 0.1 to 0

We then build the final R package with these 3 functions using the package `devtools`. 




